CC=gcc
CFLAGS= -Wall -g

all: zad1 zad2 zad3

zad1: zad1.o

zad1.o : zad1.c
	$(CC) $(CFLAGS) -c -o $@ $<

zad2: zad2.o

zad2.o : zad2.c

zad3 : zad3.o
	
zad3.o : zad3.c
	$(CC) $(CFLAGS) -c - o $@ $<


